### ISSUE TITLE
gate CNOT not supported 

### ISSUE THREAD

**Issue by sassan72** [PennyLaneAI/pennylane-aqt#14]
i am using Pennylane_aqt for my simulation. i got this error:
File "/home/anaconda3/lib/python3.7/site-packages/pennylane/_device.py", line 673, in check_validity
    "Gate {} not supported on device {}".format(operation_name, self.short_name)
pennylane._device.DeviceError: Gate CNOT not supported on device pennylane_aqt.Simulator

**Comment by antalszava** [comment]
Hi @sassan72, @rmoyard added a fix for this to the `master` branch. Until we release the plugin, the feature is accessible by cloning the repository and installing the project via `pip install -e .`. I'll be closing this issue, but let us know if you have any more questions/updates! :slightly_smiling_face:
