### ISSUE TITLE
execution of a quantum circuit with pennylane-aqt

### ISSUE THREAD

**Issue by sassan72** [PennyLaneAI/pennylane-aqt#17]
i want to run this quantum circuit with pennylane-aqt plugin. Here is the code:

```python
def ops(X):
    qml.templates.MottonenStatePreparation(X, wires=[1, 2, 3])

ops1 = qml.ctrl(ops, control=0)


@qml.qnode(dev)
def circuit(X1, X2):
    qml.Hadamard(wires=0)
    ops1(X1)
    qml.PauliX(wires=0)
    ops1(X2)
    qml.PauliX(wires=0)
    qml.Hadamard(wires=0)
    return qml.expval(qml.PauliZ(0))
```
i can run it without error with pennylane. But when i used pennylane-aqt plugin, i encountered this error:

```
File "/home/anaconda3/lib/python3.7/site-packages/pennylane_aqt/device.py", line 181, in apply
    self.samples = job["samples"] KeyError: 'samples'
```

**Comment by josh146** [comment]
Hi @sassan72, thanks for reporting this!

Can I ask what version of PennyLane and the AQT plugin you are using? This can be found by running `qml.about()`.

**Comment by sassan72** [comment]
Pennylane 0.16.0, PennyLane-AQT 0.15.0.

**Comment by sassan72** [comment]
Name: PennyLane-AQT
Version: 0.15.0

**Comment by co9olguy** [comment]
Thanks @sassan72, the team is taking a look into what could be the issue here

**Comment by antalszava** [comment]
Hi @sassan72, this should now be fixed on the `master` branch. 🙂
