### ISSUE TITLE
TypeError: Object of type tensor is not JSON serializable

### ISSUE THREAD

**Issue by sassan72** [PennyLaneAI/pennylane-aqt#23]
i ran a simple quantum circuit with pennylane-aqt and the i encountered this error.

raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type tensor is not JSON serializable

**Comment by sassan72** [comment]
Hi @antalszava have installed the 0.15.0 version. i have to upgrade it to 0.19.0. How can i do this? i tried i couldn't.

**Comment by antalszava** [comment]
If you're using `pip`, `pip install pennylane-aqt --upgrade` should work. :slightly_smiling_face: The most recent released version of this plugin is v0.18.0.

**Comment by sassan72** [comment]
i did that. it didn't work.
raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type tensor is not JSON serializable

**Comment by sassan72** [comment]
here is the circuit:

def ops(X):
    
    qml.templates.MottonenStatePreparation(X, wires=[1, 2])
    

ops1 = qml.ctrl(ops, control=0)


@qml.qnode(dev)
def circuit(X1, X2):

    qml.Hadamard(wires=0)

    ops1(X1)
    
    qml.PauliX(wires=0)
    
    ops1(X2)
    
   
    qml.PauliX(wires=0)

    
    qml.Hadamard(wires=0)
    
    
    return qml.expval(qml.PauliZ(0))

**Comment by sassan72** [comment]
"/home/user/anaconda3/lib/python3.7/json/encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type tensor is not JSON serializable

**Comment by sassan72** [comment]
i ran the code with your input successfully. i think problem is after this part of code

D1 = []

for x1 in x1_train:
    for x2 in X_test:
        a = circuit(x1, x2)
        D1.append(a)


D2 = []

for x1 in x2_train:
    for x2 in X_test:
        b = circuit(x1, x2)
        D2.append(b)

**Comment by antalszava** [comment]
Thanks! Could you send through `x1_train`, `X_test` and `x2_train`? All their minimalized versions that raise the error.

**Comment by sassan72** [comment]
import numpy as np
import pennylane as qml
import matplotlib
import sklearn.datasets
import sklearn.decomposition

import math
from sklearn import metrics
from pennylane_aqt import ops



num_qubits = 3



dev = qml.device("aqt.noisy_sim", wires=num_qubits, shots=10, api_key = "")


data1 = np.loadtxt("CERVICAL-F16-REC-ORIGINAL-1x.txt") # import pandas as pd

#df = pd.read_csv (r'Path where the CSV file is stored\File name.csv')

data2 = np.loadtxt("CERVICAL-F16-REC-ORIGINAL-1y.txt") #

data3 = np.loadtxt("CERVICAL-F16-REC-ORIGINAL-1x-test.txt") #

data4 = np.loadtxt("CERVICAL-F16-REC-ORIGINAL-1y-test.txt") #

y_train= data2[:,] 

X_train2=data1[:]

y_test= data4[:,] 

X_test2=data3[:]

X_train1 = sklearn.preprocessing.normalize(X_train2, norm='l2',axis=0)

X_test1 = sklearn.preprocessing.normalize(X_test2, norm='l2', axis=0)

X_train = sklearn.preprocessing.normalize(X_train1, norm='l2',axis=1)

X_test = sklearn.preprocessing.normalize(X_test1, norm='l2', axis=1)

x1_train=[]
x2_train=[]

for i in range(len(X_train)):
    if y_train[i]==1:
        a=X_train[i]
        x1_train.append(a)
    else:
        b=X_train[i]
        x2_train.append(b)
        
def ops(X):
    
    qml.templates.MottonenStatePreparation(X, wires=[1, 2])
    

ops1 = qml.ctrl(ops, control=0)


@qml.qnode(dev)
def circuit(X1, X2):

    qml.Hadamard(wires=0)

    ops1(X1)
    
    qml.PauliX(wires=0)
    
    ops1(X2)
    
   
    qml.PauliX(wires=0)

    
    qml.Hadamard(wires=0)
    
    
    return qml.expval(qml.PauliZ(0))


D1 = []

for x1 in x1_train:
    for x2 in X_test:
        a = circuit(x1, x2)
        D1.append(a)


D2 = []

for x1 in x2_train:
    for x2 in X_test:
        b = circuit(x1, x2)
        D2.append(b)


D11 = np.reshape(D1, (len(x1_train), len(X_test)))
D22 = np.reshape(D2, (len(x2_train), len(X_test)))

d11 = np.max(D11, axis=0)
d22 = np.max(D22, axis=0)
m = len(X_test)

Prediction=[]
for i in range(m):
    if d11[i] >= d22[i]:
        Prediction.append(1)
    else:
        Prediction.append(0)
    
BB = metrics.confusion_matrix(y_test, Prediction, labels=[0,1])

print(Prediction)



print(BB)      

#print(wires, type(wires))

**Comment by sassan72** [comment]
x-special/nautilus-clipboard
copy
file:///home/smoradi/Videos/mri/video/DATA/noise/bONEDATA/BONEMARROW-F16-ORIGINAL/iris2/CERVICAL-F16-REC-ORIGINAL-1x.txt
file:///home/smoradi/Videos/mri/video/DATA/noise/bONEDATA/BONEMARROW-F16-ORIGINAL/iris2/CERVICAL-F16-REC-ORIGINAL-1x-test.txt
file:///home/smoradi/Videos/mri/video/DATA/noise/bONEDATA/BONEMARROW-F16-ORIGINAL/iris2/CERVICAL-F16-REC-ORIGINAL-1y.txt
file:///home/smoradi/Videos/mri/video/DATA/noise/bONEDATA/BONEMARROW-F16-ORIGINAL/iris2/CERVICAL-F16-REC-ORIGINAL-1y-test.txt

**Comment by sassan72** [comment]
i don't know how to attach the data?

**Comment by sassan72** [comment]
data are iris dataset.

**Comment by sassan72** [comment]
[CERVICAL-F16-REC-ORIGINAL-1y-test.txt](https://github.com/PennyLaneAI/pennylane-aqt/files/8072114/CERVICAL-F16-REC-ORIGINAL-1y-test.txt)
[CERVICAL-F16-REC-ORIGINAL-1y.txt](https://github.com/PennyLaneAI/pennylane-aqt/files/8072115/CERVICAL-F16-REC-ORIGINAL-1y.txt)
[CERVICAL-F16-REC-ORIGINAL-1x-test.txt](https://github.com/PennyLaneAI/pennylane-aqt/files/8072116/CERVICAL-F16-REC-ORIGINAL-1x-test.txt)
[CERVICAL-F16-REC-ORIGINAL-1x.txt](https://github.com/PennyLaneAI/pennylane-aqt/files/8072117/CERVICAL-F16-REC-ORIGINAL-1x.txt)

**Comment by sassan72** [comment]
many thanks in advance.

**Comment by CatalinaAlbornoz** [comment]
Hi @sassan72 , what Python version are you using? It might help to create a new virtual environment with Python 3.9 and install the libraries you need there.

Please let me know if this solves your issue or if it persists.

**Comment by sassan72** [comment]
Python 3.7.7

**Comment by CatalinaAlbornoz** [comment]
Hi @sassan72, Python 3.7 should work. Sometimes if you create a new virtual environment and install only the libraries you need it can solve your problem. If you try this option does the problem get fixed?

**Comment by sassan72** [comment]
i will try with it and get back to you.

**Comment by CatalinaAlbornoz** [comment]
Sure! If you're using conda you can do `conda create --name <your virtual environment name> python=3.9`. You can try with Python 3.7 or 3.9 and see if that works.

**Comment by sassan72** [comment]
thanks. i did it. i got this error.
File "/home/user/anaconda3/envs/sasan/lib/python3.9/site-packages/requests/adapters.py", line 532, in send
    raise ReadTimeout(e, request=request)
requests.exceptions.ReadTimeout: HTTPSConnectionPool(host='gateway.aqt.eu', port=443): Read timed out. (read timeout=1.0)

**Comment by albi3ro** [comment]
Or something like

```python
try:
    a = circuit(x1, x2)
except requests.TimeoutError:
    time.sleep(5)
    try:
        a = circuit(x1, x2)
    except requests.TimeoutError:
        time.sleep(5)
        a = circuit(x1, x2)
```

Or better written than that.

**Comment by antalszava** [comment]
No worries, glad it worked out! :slightly_smiling_face:
